#!/usr/bin/env bash
# 将 modstore.service 对齐到与 remote_sync_extract.sh 相同的 MODstore_deploy 目录（drop-in 覆盖）。
# 需 root。用法（在服务器上）：
#   sudo MODSTORE_DEPLOY_DIR=/root/modstore-git/MODstore_deploy bash scripts/align_modstore_systemd_to_deploy.sh
# 可选环境变量：
#   MODSTORE_UVICORN_PORT   默认 9999
#   MODSTORE_UVICORN_EXTRA  追加到 uvicorn 的额外参数（整段，注意引号），如 '--workers 2'
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "[err] must run as root (systemd drop-in)" >&2
  exit 1
fi

DEPLOY_DIR="${MODSTORE_DEPLOY_DIR:-/root/modstore-git/MODstore_deploy}"
PORT="${MODSTORE_UVICORN_PORT:-9999}"
EXTRA="${MODSTORE_UVICORN_EXTRA:-}"

if [ ! -d "$DEPLOY_DIR" ]; then
  echo "[err] not a directory: $DEPLOY_DIR" >&2
  exit 1
fi
if [ ! -x "$DEPLOY_DIR/.venv/bin/python" ]; then
  echo "[err] missing venv: $DEPLOY_DIR/.venv/bin/python (先在该目录 pip install -e '.[web,knowledge]')" >&2
  exit 1
fi
if [ ! -f "$DEPLOY_DIR/modstore_server/app.py" ]; then
  echo "[err] not a MODstore_deploy tree: $DEPLOY_DIR" >&2
  exit 1
fi

DROP_DIR="/etc/systemd/system/modstore.service.d"
CONF="$DROP_DIR/99-modstore-deploy-dir.conf"

mkdir -p "$DROP_DIR"
if [ -f "$CONF" ]; then
  bak="/tmp/99-modstore-deploy-dir.conf.bak.$(date +%s)"
  cp -a "$CONF" "$bak"
  echo "[ok] backed up existing $CONF -> $bak"
fi

# systemd: ExecStart= 空行清除继承，下一行写入新命令
EXEC_CMD="$DEPLOY_DIR/.venv/bin/python -m uvicorn modstore_server.app:app --host 0.0.0.0 --port $PORT"
if [ -n "$EXTRA" ]; then
  EXEC_CMD="$EXEC_CMD $EXTRA"
fi

umask 022
cat >"$CONF" <<EOF
# Generated by align_modstore_systemd_to_deploy.sh — 与 sync 解压目录对齐
[Service]
WorkingDirectory=$DEPLOY_DIR
ExecStart=
ExecStart=$EXEC_CMD
EOF

echo "[ok] wrote $CONF"
systemctl daemon-reload
systemctl restart modstore
sleep 2
systemctl is-active modstore || true
code=$(curl -sS -o /dev/null -m 5 -w "%{http_code}" "http://127.0.0.1:${PORT}/api/health" 2>/dev/null || true)
code=${code:-000}
echo "[ok] curl http://127.0.0.1:${PORT}/api/health -> $code"
if [ "$code" != "200" ]; then
  echo "[warn] health not 200; check journal: journalctl -u modstore -n 80 --no-pager" >&2
  exit 1
fi
echo "[ok] align done"
