"""employee_pack 内 ``backend/blueprints.py`` + ``backend/employees/<stem>.py`` 模板（与 FHD smoke mod 路由契约对齐）。"""

from __future__ import annotations

import json
import re
from typing import Any, Dict


def render_employee_pack_employee_py(
    *,
    employee_id: str,
    stem: str,
    label: str,
) -> str:
    """最小可运行 ``run``：优先读 manifest ``employee_config_v2`` 并走 ``ctx.call_llm``。"""
    label_lit = json.dumps(label or employee_id, ensure_ascii=False)
    return (
        '"""employee_pack 员工实现（MODstore 生成）。"""\n'
        "from __future__ import annotations\n\n"
        "import json\n"
        "import logging\n"
        "from pathlib import Path\n"
        "from typing import Any, Dict, Optional\n\n"
        "logger = logging.getLogger(__name__)\n\n"
        "EMPLOYEE_ID = " + json.dumps(employee_id, ensure_ascii=False) + "\n"
        "EMPLOYEE_LABEL = " + label_lit + "\n\n\n"
        "def _manifest_path() -> Path:\n"
        "    here = Path(__file__).resolve()\n"
        "    return here.parents[1] / 'manifest.json'\n\n\n"
        "def _load_employee_config_v2() -> Optional[Dict[str, Any]]:\n"
        "    mp = _manifest_path()\n"
        "    if not mp.is_file():\n"
        "        return None\n"
        "    try:\n"
        "        data = json.loads(mp.read_text(encoding='utf-8'))\n"
        "    except (OSError, json.JSONDecodeError):\n"
        "        return None\n"
        "    v2 = data.get('employee_config_v2')\n"
        "    return v2 if isinstance(v2, dict) else None\n\n\n"
        "def _v2_system_prompt(v2: Dict[str, Any]) -> str:\n"
        "    cog = v2.get('cognition') if isinstance(v2.get('cognition'), dict) else {}\n"
        "    agent = cog.get('agent') if isinstance(cog.get('agent'), dict) else {}\n"
        "    sp = agent.get('system_prompt')\n"
        "    if isinstance(sp, str) and sp.strip():\n"
        "        return sp.strip()\n"
        '    return "你是宿主员工助手：" + EMPLOYEE_LABEL + "。根据用户 payload 给出简明结构化结果。"\n\n\n'
        "async def run(payload: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    logger.info('[employee:%s] run keys=%s', EMPLOYEE_ID, list((payload or {}).keys())[:12])\n"
        "    v2 = _load_employee_config_v2()\n"
        "    call_llm = ctx.get('call_llm')\n"
        "    if v2 and callable(call_llm):\n"
        "        user_msg = json.dumps(payload or {}, ensure_ascii=False)[:6000]\n"
        "        messages = [\n"
        "            {'role': 'system', 'content': _v2_system_prompt(v2)},\n"
        "            {'role': 'user', 'content': user_msg},\n"
        "        ]\n"
        "        res = await call_llm(messages, max_tokens=2048, temperature=0.2)\n"
        "        if isinstance(res, dict) and res.get('ok'):\n"
        "            return {\n"
        "                'summary': str(res.get('content') or '').strip()[:4000],\n"
        "                'items': [],\n"
        "                'warnings': [],\n"
        "                'employee_config_v2_used': True,\n"
        "            }\n"
        "        return {\n"
        "            'summary': 'LLM 调用失败',\n"
        "            'items': [],\n"
        "            'warnings': ['call_llm_failed'],\n"
        "            'error': str((res or {}).get('error') or '')[:400],\n"
        "        }\n"
        "    return {\n"
        "        'summary': 'echo: ' + EMPLOYEE_LABEL,\n"
        "        'items': [{'echo': payload}],\n"
        "        'warnings': ['no_v2_or_no_call_llm'],\n"
        "    }\n"
    )


def render_employee_pack_blueprints_py(*, pack_id: str, employee_id: str, stem: str, label: str) -> str:
    """单员工 ``register_fastapi_routes``。"""
    _ = pack_id
    emp_lit = json.dumps(employee_id, ensure_ascii=False)
    stem_lit = json.dumps(stem, ensure_ascii=False)
    lab_lit = json.dumps(label or employee_id, ensure_ascii=False)
    return (
        '"""employee_pack HTTP 面（MODstore 生成）。"""\n'
        "from __future__ import annotations\n\n"
        "import asyncio\n"
        "import logging\n"
        "import os\n"
        "from typing import Any, Dict, Optional\n\n"
        "from fastapi import APIRouter\n\n"
        "logger = logging.getLogger(__name__)\n\n"
        "EMPLOYEE_ID = " + emp_lit + "\n"
        "STEM = " + stem_lit + "\n"
        "LABEL = " + lab_lit + "\n\n\n"
        "def _resolve_mod_path(mod_id: str) -> Optional[str]:\n"
        "    try:\n"
        "        from app.infrastructure.mods import get_mod_registry  # type: ignore\n\n"
        "        meta = get_mod_registry().get_mod_metadata(mod_id)\n"
        "        mp = getattr(meta, 'mod_path', '') or ''\n"
        "        if mp and os.path.isdir(mp):\n"
        "            return mp\n"
        "    except Exception:\n"
        "        pass\n"
        "    here = os.path.dirname(os.path.abspath(__file__))\n"
        "    guess = os.path.dirname(here)\n"
        "    return guess if os.path.isdir(guess) else None\n\n\n"
        "def _load_employee_module(mod_id: str, stem: str):\n"
        "    try:\n"
        "        from app.mod_sdk.mods_bus import import_mod_backend_py  # type: ignore\n"
        "    except ImportError:\n"
        "        return None\n"
        "    mod_path = _resolve_mod_path(mod_id)\n"
        "    if not mod_path:\n"
        "        return None\n"
        "    try:\n"
        '        return import_mod_backend_py(mod_path, mod_id, f"employees/{stem}")\n'
        "    except Exception:\n"
        "        logger.exception('load employee module failed stem=%s', stem)\n"
        "        return None\n\n\n"
        "async def _dispatch_run(mod_id: str, emp_id: str, stem: str, payload: Optional[Dict[str, Any]]):\n"
        "    module = _load_employee_module(mod_id, stem)\n"
        "    if module is None or not hasattr(module, 'run'):\n"
        "        return {\n"
        "            'success': False,\n"
        "            'error': 'employee module not loaded',\n"
        "            'hint': '请确认 backend/employees 下存在对应 .py 并实现 async def run。',\n"
        "        }\n"
        "    ctx = {\n"
        "        'mod_id': mod_id,\n"
        "        'employee_id': emp_id,\n"
        "        'logger': logging.getLogger(f'mod.{mod_id}.emp.{emp_id}'),\n"
        "        'call_llm': None,\n"
        "        'http_get': None,\n"
        "        'http_post': None,\n"
        "        'secrets': None,\n"
        "    }\n"
        "    call_llm_available = False\n"
        "    try:\n"
        "        from app.mod_sdk.mod_employee_llm import mod_employee_complete  # type: ignore\n\n"
        "        async def _call_llm(messages, *, max_tokens=1024, temperature=0.2, response_format=None):\n"
        "            return await mod_employee_complete(\n"
        "                messages, max_tokens=max_tokens, temperature=temperature, response_format=response_format\n"
        "            )\n\n"
        "        ctx['call_llm'] = _call_llm\n"
        "        call_llm_available = True\n"
        "    except Exception as _e:\n"
        "        logger.warning('mod_employee_complete 不可用，call_llm 将使用降级：%s', _e)\n"
        "    if not call_llm_available:\n"
        "        async def _call_llm_disabled(messages, **kwargs):\n"
        "            return {'ok': False, 'content': '', 'error': '宿主 LLM 服务不可用（mod_employee_complete 导入失败），请检查 API Key 与 mod_employee_llm 配置'}\n"
        "        ctx['call_llm'] = _call_llm_disabled\n"
        "    try:\n"
        "        import httpx as _httpx\n\n"
        "        async def _http_get(url, *, headers=None, timeout=30):\n"
        "            try:\n"
        "                async with _httpx.AsyncClient(timeout=float(timeout)) as _c:\n"
        "                    r = await _c.get(url, headers=headers or {})\n"
        "                    return {'ok': r.status_code < 400, 'status': r.status_code, 'text': r.text, 'error': ''}\n"
        "            except Exception as _e:\n"
        "                return {'ok': False, 'status': 0, 'text': '', 'error': str(_e)[:500]}\n\n"
        "        async def _http_post(url, *, json_body=None, data=None, headers=None, timeout=30):\n"
        "            try:\n"
        "                async with _httpx.AsyncClient(timeout=float(timeout)) as _c:\n"
        "                    r = await _c.post(url, json=json_body, data=data, headers=headers or {})\n"
        "                    return {'ok': r.status_code < 400, 'status': r.status_code, 'text': r.text, 'error': ''}\n"
        "            except Exception as _e:\n"
        "                return {'ok': False, 'status': 0, 'text': '', 'error': str(_e)[:500]}\n\n"
        "        ctx['http_get'] = _http_get\n"
        "        ctx['http_post'] = _http_post\n"
        "    except ImportError:\n"
        "        logger.warning('httpx 不可用，http_get/http_post 使用降级')\n\n"
        "        async def _http_disabled(url, **kwargs):\n"
        "            return {'ok': False, 'status': 0, 'text': '', 'error': 'httpx 未安装，HTTP 请求不可用'}\n\n"
        "        ctx['http_get'] = _http_disabled\n"
        "        ctx['http_post'] = _http_disabled\n"
        "    try:\n"
        "        run_fn = getattr(module, 'run')\n"
        "        out = run_fn(payload or {}, ctx)\n"
        "        if asyncio.iscoroutine(out):\n"
        "            out = await out\n"
        "        return {'success': True, 'data': out}\n"
        "    except Exception as e:  # noqa: BLE001\n"
        "        logger.exception('employee run failed')\n"
        "        return {'success': False, 'error': str(e)[:500]}\n\n\n"
        "def register_fastapi_routes(app, mod_id: str) -> None:\n"
        '    router = APIRouter(prefix=f"/api/mod/{mod_id}", tags=[f"emp-pack-{mod_id}"])\n'
        "    emp_id = EMPLOYEE_ID\n"
        "    stem = STEM\n\n"
        "    @router.get('/employees')\n"
        "    async def list_employees():\n"
        "        return {'success': True, 'data': [{'id': emp_id, 'label': LABEL, 'summary': ''}]}\n\n"
        "    @router.post('/employees/' + emp_id + '/run')\n"
        "    async def emp_run(payload: Dict[str, Any] | None = None):\n"
        "        return await _dispatch_run(mod_id, emp_id, stem, payload)\n\n"
        "    @router.get('/employees/' + emp_id + '/status')\n"
        "    async def emp_status():\n"
        "        return {'success': True, 'data': {'employee_id': emp_id, 'status': 'ready'}}\n\n"
        "    app.include_router(router)\n"
        '    logger.info("employee_pack routes registered mod_id=%s emp=%s", mod_id, emp_id)\n\n\n'
        "def mod_init():\n"
        "    logger.info('employee_pack backend init')\n"
    )
