"""employee_pack 内 ``backend/blueprints.py`` + ``backend/employees/<stem>.py`` 模板（与 FHD smoke mod 路由契约对齐）。"""

from __future__ import annotations

import json
import re
from typing import Any, Dict


def render_employee_pack_employee_py(
    *,
    employee_id: str,
    stem: str,
    label: str,
) -> str:
    """生成员工 ``run``：从 manifest 注入 model 配置，按 actions.handlers 分支，统一返回 schema。

    生成的代码满足 Phase 1 修复：
    - manifest 路径向上查找直到 manifest.json（修 #8）
    - 从 ``employee_config_v2.cognition.agent.model`` 注入 max_tokens/temperature/system_prompt（修 #7、#2 第一层）
    - ``await call_llm`` 用 try/except 包裹，超时/异常统一返回（修 #5）
    - 三种场景统一返回 ``{ok, summary, items, warnings, error, meta}``（修 #6）
    - 按 ``actions.handlers`` 真实分支：echo / llm_md / webhook，未声明报错而非默认 LLM（修 #3）
    - 加载失败时由 blueprints 统一返回 ``{ok: False, error: ...}``，与本模块的统一 schema 对齐（修 #4）
    """
    label_lit = json.dumps(label or employee_id, ensure_ascii=False)
    return (
        '"""employee_pack 员工实现（MODstore 生成）。\n\n'
        '行为按 manifest.employee_config_v2.actions.handlers 分支：\n'
        '  - echo     → 直接回显 payload，不调 LLM\n'
        '  - llm_md   → 调 ctx.call_llm 出 Markdown（默认章节：用途/输入/输出/示例/异常）\n'
        '  - webhook  → 调 ctx.http_post 转发到 actions.webhook.url\n'
        '若 handlers 为空或不被支持，run 返回 {ok: False, error: ...}，绝不默认走 LLM。\n'
        '"""\n'
        "from __future__ import annotations\n\n"
        "import asyncio\n"
        "import json\n"
        "import logging\n"
        "from pathlib import Path\n"
        "from typing import Any, Dict, List, Optional\n\n"
        "logger = logging.getLogger(__name__)\n\n"
        "EMPLOYEE_ID = " + json.dumps(employee_id, ensure_ascii=False) + "\n"
        "EMPLOYEE_LABEL = " + label_lit + "\n\n"
        "DEFAULT_README_SECTIONS = (\n"
        "    '## 用途\\n'\n"
        "    '## 输入\\n'\n"
        "    '## 输出\\n'\n"
        "    '## 示例\\n'\n"
        "    '## 异常与边界\\n'\n"
        ")\n\n\n"
        "def _ok(data: Any, *, warnings: Optional[List[str]] = None, meta: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:\n"
        "    return {\n"
        "        'ok': True,\n"
        "        'summary': '' if data is None else (data if isinstance(data, str) else json.dumps(data, ensure_ascii=False))[:4000],\n"
        "        'items': data if isinstance(data, list) else ([] if data is None else [data] if not isinstance(data, dict) else [data]),\n"
        "        'warnings': list(warnings or []),\n"
        "        'error': '',\n"
        "        'meta': dict(meta or {}),\n"
        "    }\n\n\n"
        "def _err(msg: str, *, warnings: Optional[List[str]] = None, meta: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:\n"
        "    return {\n"
        "        'ok': False,\n"
        "        'summary': msg[:400],\n"
        "        'items': [],\n"
        "        'warnings': list(warnings or []),\n"
        "        'error': msg[:1000],\n"
        "        'meta': dict(meta or {}),\n"
        "    }\n\n\n"
        "def _manifest_path() -> Optional[Path]:\n"
        "    here = Path(__file__).resolve()\n"
        "    for parent in (here.parent, *here.parents):\n"
        "        cand = parent / 'manifest.json'\n"
        "        if cand.is_file():\n"
        "            return cand\n"
        "    return None\n\n\n"
        "def _load_manifest() -> Optional[Dict[str, Any]]:\n"
        "    mp = _manifest_path()\n"
        "    if not mp:\n"
        "        return None\n"
        "    try:\n"
        "        data = json.loads(mp.read_text(encoding='utf-8'))\n"
        "    except (OSError, json.JSONDecodeError):\n"
        "        return None\n"
        "    return data if isinstance(data, dict) else None\n\n\n"
        "def _v2(manifest: Optional[Dict[str, Any]]) -> Dict[str, Any]:\n"
        "    if not isinstance(manifest, dict):\n"
        "        return {}\n"
        "    v2 = manifest.get('employee_config_v2')\n"
        "    return v2 if isinstance(v2, dict) else {}\n\n\n"
        "def _agent_model(v2: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    cog = v2.get('cognition') if isinstance(v2.get('cognition'), dict) else {}\n"
        "    agent = cog.get('agent') if isinstance(cog.get('agent'), dict) else {}\n"
        "    model = agent.get('model') if isinstance(agent.get('model'), dict) else {}\n"
        "    return {\n"
        "        'system_prompt': str(agent.get('system_prompt') or '').strip(),\n"
        "        'max_tokens': int(model.get('max_tokens') or 4000),\n"
        "        'temperature': float(model.get('temperature') if model.get('temperature') is not None else 0.2),\n"
        "    }\n\n\n"
        "def _actions(v2: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    a = v2.get('actions') if isinstance(v2.get('actions'), dict) else {}\n"
        "    return a\n\n\n"
        "def _handlers(actions: Dict[str, Any]) -> List[str]:\n"
        "    raw = actions.get('handlers') if isinstance(actions.get('handlers'), list) else []\n"
        "    return [str(h).strip() for h in raw if isinstance(h, str) and str(h).strip()]\n\n\n"
        "async def _handle_echo(payload: Dict[str, Any], _ctx: Dict[str, Any], _v2: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    return _ok({'echo': payload}, meta={'handler': 'echo'})\n\n\n"
        "async def _handle_llm_md(payload: Dict[str, Any], ctx: Dict[str, Any], v2: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    call_llm = ctx.get('call_llm')\n"
        "    if not callable(call_llm):\n"
        "        summary = [\n"
        "            f'# {EMPLOYEE_LABEL} 执行方案',\n"
        "            '',\n"
        "            '宿主未注入 ctx.call_llm，本次以离线方案模式运行。',\n"
        "            '',\n"
        "            '## 输入',\n"
        "            json.dumps(payload or {}, ensure_ascii=False, indent=2)[:3000],\n"
        "            '',\n"
        "            '## 下一步',\n"
        "            '- 在宿主上下文注入 call_llm 后，可由 llm_md 生成完整 Markdown 结果。',\n"
        "            '- 也可通过 payload.handler=echo 获取原始输入回显。',\n"
        "        ]\n"
        "        return _ok('\\n'.join(summary), warnings=['ctx.call_llm unavailable; returned offline plan'], meta={'handler': 'llm_md', 'offline': True})\n"
        "    cfg = _agent_model(v2)\n"
        "    sys_prompt = cfg['system_prompt'] or (\n"
        "        '你是宿主员工助手：' + EMPLOYEE_LABEL + '。\\n请输出 Markdown，章节固定为：\\n' + DEFAULT_README_SECTIONS\n"
        "    )\n"
        "    if '##' not in sys_prompt:\n"
        "        sys_prompt = sys_prompt + '\\n\\n请用 Markdown 输出，固定章节：\\n' + DEFAULT_README_SECTIONS\n"
        "    user_msg = json.dumps(payload or {}, ensure_ascii=False)[:6000]\n"
        "    messages = [\n"
        "        {'role': 'system', 'content': sys_prompt},\n"
        "        {'role': 'user', 'content': user_msg},\n"
        "    ]\n"
        "    try:\n"
        "        res = await asyncio.wait_for(\n"
        "            call_llm(messages, max_tokens=cfg['max_tokens'], temperature=cfg['temperature']),\n"
        "            timeout=120.0,\n"
        "        )\n"
        "    except asyncio.TimeoutError:\n"
        "        return _err('LLM 调用超时（120s）', meta={'handler': 'llm_md'})\n"
        "    except Exception as e:  # noqa: BLE001\n"
        "        logger.exception('call_llm raised')\n"
        "        return _err('LLM 调用异常：' + str(e)[:300], meta={'handler': 'llm_md'})\n"
        "    if not isinstance(res, dict) or not res.get('ok'):\n"
        "        return _err(str((res or {}).get('error') or 'LLM 调用失败')[:400], meta={'handler': 'llm_md'})\n"
        "    content = str(res.get('content') or '').strip()\n"
        "    return _ok(content, meta={'handler': 'llm_md', 'max_tokens': cfg['max_tokens']})\n\n\n"
        "async def _handle_webhook(payload: Dict[str, Any], ctx: Dict[str, Any], v2: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    http_post = ctx.get('http_post')\n"
        "    if not callable(http_post):\n"
        "        return _err('ctx.http_post 不可用：宿主未注入 HTTP 能力', meta={'handler': 'webhook'})\n"
        "    cfg = _actions(v2).get('webhook') if isinstance(_actions(v2).get('webhook'), dict) else {}\n"
        "    url = str(cfg.get('url') or '').strip()\n"
        "    if not url:\n"
        "        return _err('actions.webhook.url 未配置', meta={'handler': 'webhook'})\n"
        "    try:\n"
        "        r = await asyncio.wait_for(http_post(url, json_body=payload or {}), timeout=30.0)\n"
        "    except asyncio.TimeoutError:\n"
        "        return _err('webhook 超时（30s）', meta={'handler': 'webhook', 'url': url})\n"
        "    except Exception as e:  # noqa: BLE001\n"
        "        return _err('webhook 异常：' + str(e)[:300], meta={'handler': 'webhook', 'url': url})\n"
        "    if not isinstance(r, dict) or not r.get('ok'):\n"
        "        return _err(str((r or {}).get('error') or f\"HTTP {(r or {}).get('status')}\"), meta={'handler': 'webhook', 'url': url})\n"
        "    return _ok({'status': r.get('status'), 'text': r.get('text')}, meta={'handler': 'webhook', 'url': url})\n\n\n"
        "async def _handle_agent(payload: Dict[str, Any], ctx: Dict[str, Any], v2: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    runner = ctx.get('agent_runner')\n"
        "    if runner is None:\n"
        "        return _err('ctx.agent_runner 未注入，请确认 modstore_server 版本', meta={'handler': 'agent'})\n"
        "    cfg = _agent_model(v2)\n"
        "    task = (\n"
        "        payload.get('task') or payload.get('message') or payload.get('input')\n"
        "        or json.dumps(payload or {}, ensure_ascii=False)[:2000]\n"
        "    )\n"
        "    sys_prompt = cfg['system_prompt'] or f'你是宿主员工：{EMPLOYEE_LABEL}。根据用户任务，逐步使用可用工具完成工作，给出真实结果。'\n"
        "    try:\n"
        "        result = await asyncio.wait_for(\n"
        "            runner.run(task, system_prompt=sys_prompt),\n"
        "            timeout=300.0,\n"
        "        )\n"
        "    except asyncio.TimeoutError:\n"
        "        return _err('agent 执行超时（300s）', meta={'handler': 'agent'})\n"
        "    except Exception as e:  # noqa: BLE001\n"
        "        logger.exception('agent run raised')\n"
        "        return _err('agent 执行异常：' + str(e)[:300], meta={'handler': 'agent'})\n"
        "    if not result.get('ok'):\n"
        "        return _err(str(result.get('error') or 'agent 失败'), meta={'handler': 'agent', 'rounds': result.get('rounds', 0)})\n"
        "    return _ok(\n"
        "        result.get('summary') or '',\n"
        "        meta={'handler': 'agent', 'rounds': result.get('rounds', 0),\n"
        "              'tools_used': [t.get('tool') for t in (result.get('tool_calls') or [])]},\n"
        "    )\n\n\n"
        "_DISPATCH = {\n"
        "    'echo': _handle_echo,\n"
        "    'llm_md': _handle_llm_md,\n"
        "    'webhook': _handle_webhook,\n"
        "    'agent': _handle_agent,\n"
        "}\n\n\n"
        "async def run(payload: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:\n"
        "    logger.info('[employee:%s] run keys=%s', EMPLOYEE_ID, list((payload or {}).keys())[:12])\n"
        "    payload = payload or {}\n"
        "    ctx = ctx or {}\n"
        "    manifest = _load_manifest()\n"
        "    v2 = _v2(manifest)\n"
        "    if not v2:\n"
        "        return _err('manifest.employee_config_v2 缺失或不可读，无法决定行为',\n"
        "                    meta={'employee_id': EMPLOYEE_ID})\n"
        "    handlers = _handlers(_actions(v2))\n"
        "    if not handlers:\n"
        "        return _err('manifest.employee_config_v2.actions.handlers 未声明；请在打包时显式声明 echo / llm_md / webhook 之一',\n"
        "                    meta={'employee_id': EMPLOYEE_ID})\n"
        "    requested = str(payload.get('handler') or '').strip() if isinstance(payload, dict) else ''\n"
        "    chosen = requested if requested in handlers else handlers[0]\n"
        "    fn = _DISPATCH.get(chosen)\n"
        "    if fn is None:\n"
        "        return _err(f\"不支持的 handler：{chosen}（支持：{sorted(_DISPATCH.keys())}）\",\n"
        "                    meta={'employee_id': EMPLOYEE_ID, 'declared_handlers': handlers})\n"
        "    out = await fn(payload, ctx, v2)\n"
        "    if isinstance(out, dict):\n"
        "        meta = out.setdefault('meta', {})\n"
        "        if isinstance(meta, dict):\n"
        "            meta.setdefault('declared_handlers', handlers)\n"
        "            meta.setdefault('chosen_handler', chosen)\n"
        "    return out\n"
    )


def render_employee_pack_blueprints_py(*, pack_id: str, employee_id: str, stem: str, label: str) -> str:
    """单员工 ``register_fastapi_routes``。"""
    _ = pack_id
    emp_lit = json.dumps(employee_id, ensure_ascii=False)
    stem_lit = json.dumps(stem, ensure_ascii=False)
    lab_lit = json.dumps(label or employee_id, ensure_ascii=False)
    return (
        '"""employee_pack HTTP 面（MODstore 生成）。"""\n'
        "from __future__ import annotations\n\n"
        "import asyncio\n"
        "import logging\n"
        "import os\n"
        "from typing import Any, Dict, Optional\n\n"
        "from fastapi import APIRouter\n\n"
        "logger = logging.getLogger(__name__)\n\n"
        "EMPLOYEE_ID = " + emp_lit + "\n"
        "STEM = " + stem_lit + "\n"
        "LABEL = " + lab_lit + "\n\n\n"
        "def _resolve_mod_path(mod_id: str) -> Optional[str]:\n"
        "    try:\n"
        "        from app.infrastructure.mods import get_mod_registry  # type: ignore\n\n"
        "        meta = get_mod_registry().get_mod_metadata(mod_id)\n"
        "        mp = getattr(meta, 'mod_path', '') or ''\n"
        "        if mp and os.path.isdir(mp):\n"
        "            return mp\n"
        "    except Exception:\n"
        "        pass\n"
        "    here = os.path.dirname(os.path.abspath(__file__))\n"
        "    guess = os.path.dirname(here)\n"
        "    return guess if os.path.isdir(guess) else None\n\n\n"
        "def _load_employee_module(mod_id: str, stem: str):\n"
        "    try:\n"
        "        from app.mod_sdk.mods_bus import import_mod_backend_py  # type: ignore\n"
        "    except ImportError:\n"
        "        return None\n"
        "    mod_path = _resolve_mod_path(mod_id)\n"
        "    if not mod_path:\n"
        "        return None\n"
        "    try:\n"
        '        return import_mod_backend_py(mod_path, mod_id, f"employees/{stem}")\n'
        "    except Exception:\n"
        "        logger.exception('load employee module failed stem=%s', stem)\n"
        "        return None\n\n\n"
        "def _unified_err(msg: str, **meta):\n"
        "    return {\n"
        "        'success': False,\n"
        "        'data': {\n"
        "            'ok': False,\n"
        "            'summary': msg[:400],\n"
        "            'items': [],\n"
        "            'warnings': [],\n"
        "            'error': msg[:1000],\n"
        "            'meta': meta,\n"
        "        },\n"
        "        'error': msg[:500],\n"
        "    }\n\n\n"
        "async def _dispatch_run(mod_id: str, emp_id: str, stem: str, payload: Optional[Dict[str, Any]]):\n"
        "    module = _load_employee_module(mod_id, stem)\n"
        "    if module is None or not hasattr(module, 'run'):\n"
        "        return _unified_err(\n"
        "            'employee module not loaded：请确认 backend/employees 下存在对应 .py 并实现 async def run',\n"
        "            employee_id=emp_id, stem=stem,\n"
        "        )\n"
        "    ctx = {\n"
        "        'mod_id': mod_id,\n"
        "        'employee_id': emp_id,\n"
        "        'logger': logging.getLogger(f'mod.{mod_id}.emp.{emp_id}'),\n"
        "        'call_llm': None,\n"
        "        'http_get': None,\n"
        "        'http_post': None,\n"
        "        'secrets': None,\n"
        "    }\n"
        "    call_llm_available = False\n"
        "    try:\n"
        "        from app.mod_sdk.mod_employee_llm import mod_employee_complete  # type: ignore\n\n"
        "        async def _call_llm(messages, *, max_tokens=1024, temperature=0.2, response_format=None):\n"
        "            return await mod_employee_complete(\n"
        "                messages, max_tokens=max_tokens, temperature=temperature, response_format=response_format\n"
        "            )\n\n"
        "        ctx['call_llm'] = _call_llm\n"
        "        call_llm_available = True\n"
        "    except Exception as _e:\n"
        "        logger.warning('mod_employee_complete 不可用，call_llm 将使用降级：%s', _e)\n"
        "    if not call_llm_available:\n"
        "        async def _call_llm_disabled(messages, **kwargs):\n"
        "            return {'ok': False, 'content': '', 'error': '宿主 LLM 服务不可用（mod_employee_complete 导入失败），请检查 API Key 与 mod_employee_llm 配置'}\n"
        "        ctx['call_llm'] = _call_llm_disabled\n"
        "    try:\n"
        "        import httpx as _httpx\n\n"
        "        async def _http_get(url, *, headers=None, timeout=30):\n"
        "            try:\n"
        "                async with _httpx.AsyncClient(timeout=float(timeout)) as _c:\n"
        "                    r = await _c.get(url, headers=headers or {})\n"
        "                    return {'ok': r.status_code < 400, 'status': r.status_code, 'text': r.text, 'error': ''}\n"
        "            except Exception as _e:\n"
        "                return {'ok': False, 'status': 0, 'text': '', 'error': str(_e)[:500]}\n\n"
        "        async def _http_post(url, *, json_body=None, data=None, headers=None, timeout=30):\n"
        "            try:\n"
        "                async with _httpx.AsyncClient(timeout=float(timeout)) as _c:\n"
        "                    r = await _c.post(url, json=json_body, data=data, headers=headers or {})\n"
        "                    return {'ok': r.status_code < 400, 'status': r.status_code, 'text': r.text, 'error': ''}\n"
        "            except Exception as _e:\n"
        "                return {'ok': False, 'status': 0, 'text': '', 'error': str(_e)[:500]}\n\n"
        "        ctx['http_get'] = _http_get\n"
        "        ctx['http_post'] = _http_post\n"
        "    except ImportError:\n"
        "        logger.warning('httpx 不可用，http_get/http_post 使用降级')\n\n"
        "        async def _http_disabled(url, **kwargs):\n"
        "            return {'ok': False, 'status': 0, 'text': '', 'error': 'httpx 未安装，HTTP 请求不可用'}\n\n"
        "        ctx['http_get'] = _http_disabled\n"
        "        ctx['http_post'] = _http_disabled\n"
        # ── Workspace tools ─────────────────────────────────────────────────
        "    _workspace_root = (\n"
        "        os.environ.get('EMPLOYEE_WORKSPACE_ROOT', '')\n"
        "        or os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'workspace'))\n"
        "    )\n"
        "    os.makedirs(_workspace_root, exist_ok=True)\n"
        "    ctx['workspace_root'] = _workspace_root\n\n"
        "    def _guard(_p):\n"
        "        resolved = os.path.normpath(os.path.join(_workspace_root, _p))\n"
        "        if not resolved.startswith(os.path.abspath(_workspace_root) + os.sep) and resolved != os.path.abspath(_workspace_root):\n"
        "            return None\n"
        "        return resolved\n\n"
        "    async def _read_workspace_file(path):\n"
        "        r = _guard(path)\n"
        "        if r is None:\n"
        "            return {'ok': False, 'error': '路径越界'}\n"
        "        if not os.path.isfile(r):\n"
        "            return {'ok': False, 'error': f'文件不存在: {path!r}'}\n"
        "        try:\n"
        "            txt = open(r, encoding='utf-8', errors='replace').read()\n"
        "            return {'ok': True, 'path': path, 'content': txt[:8000], 'truncated': len(txt) > 8000, 'total_chars': len(txt)}\n"
        "        except OSError as e:\n"
        "            return {'ok': False, 'error': str(e)[:300]}\n\n"
        "    async def _write_workspace_file(path, content):\n"
        "        r = _guard(path)\n"
        "        if r is None:\n"
        "            return {'ok': False, 'error': '路径越界'}\n"
        "        try:\n"
        "            os.makedirs(os.path.dirname(r) or '.', exist_ok=True)\n"
        "            open(r, 'w', encoding='utf-8').write(content or '')\n"
        "            return {'ok': True, 'path': path, 'bytes_written': len((content or '').encode())}\n"
        "        except OSError as e:\n"
        "            return {'ok': False, 'error': str(e)[:300]}\n\n"
        "    async def _list_workspace_dir(path='.'):\n"
        "        r = _guard(path)\n"
        "        if r is None:\n"
        "            return {'ok': False, 'error': '路径越界'}\n"
        "        if not os.path.isdir(r):\n"
        "            return {'ok': False, 'error': f'目录不存在: {path!r}'}\n"
        "        skip = {'.git', 'node_modules', '__pycache__', '.venv', 'venv', 'dist', 'build'}\n"
        "        entries = []\n"
        "        for name in sorted(os.listdir(r))[:50]:\n"
        "            if name in skip: continue\n"
        "            full = os.path.join(r, name)\n"
        "            entries.append({'name': name, 'type': 'dir' if os.path.isdir(full) else 'file',\n"
        "                            'size': 0 if os.path.isdir(full) else os.path.getsize(full)})\n"
        "        return {'ok': True, 'path': path, 'entries': entries}\n\n"
        "    import subprocess as _sp\n"
        "    async def _run_sandboxed_python(code, timeout=10.0):\n"
        "        import re as _re\n"
        "        if _re.search(r'\\b(import\\s+subprocess|import\\s+socket|open\\s*\\(|__import__|exec\\s*\\(|eval\\s*\\()\\b', code):\n"
        "            return {'ok': False, 'error': '代码包含不允许的操作'}\n"
        "        try:\n"
        "            p = _sp.run(['python', '-c', code], capture_output=True, text=True, timeout=float(timeout),\n"
        "                        env={k: v for k, v in os.environ.items() if k in ('PATH', 'PYTHONPATH', 'TEMP', 'TMP')})\n"
        "            return {'ok': p.returncode == 0, 'stdout': p.stdout[:2000], 'stderr': p.stderr[:500], 'returncode': p.returncode}\n"
        "        except _sp.TimeoutExpired:\n"
        "            return {'ok': False, 'error': f'执行超时（{timeout:.0f}s）'}\n"
        "        except Exception as e:\n"
        "            return {'ok': False, 'error': str(e)[:300]}\n\n"
        "    ctx['read_workspace_file'] = _read_workspace_file\n"
        "    ctx['write_workspace_file'] = _write_workspace_file\n"
        "    ctx['list_workspace_dir'] = _list_workspace_dir\n"
        "    ctx['run_sandboxed_python'] = _run_sandboxed_python\n\n"
        # ── agent_runner (ReAct loop) ────────────────────────────────────────
        "    try:\n"
        "        from modstore_server.mod_employee_agent_runner import build_agent_runner  # type: ignore\n"
        "        ctx['agent_runner'] = build_agent_runner(ctx)\n"
        "    except Exception as _ar_err:\n"
        "        logger.warning('agent_runner 不可用：%s', _ar_err)\n"
        "        ctx['agent_runner'] = None\n\n"
        # ── dispatch run ────────────────────────────────────────────────────
        "    try:\n"
        "        run_fn = getattr(module, 'run')\n"
        "        out = run_fn(payload or {}, ctx)\n"
        "        if asyncio.iscoroutine(out):\n"
        "            out = await out\n"
        "        return {'success': True, 'data': out}\n"
        "    except Exception as e:  # noqa: BLE001\n"
        "        logger.exception('employee run failed')\n"
        "        return _unified_err('employee run failed: ' + str(e)[:300], employee_id=emp_id)\n\n\n"
        "def register_fastapi_routes(app, mod_id: str) -> None:\n"
        '    router = APIRouter(prefix=f"/api/mod/{mod_id}", tags=[f"emp-pack-{mod_id}"])\n'
        "    emp_id = EMPLOYEE_ID\n"
        "    stem = STEM\n\n"
        "    @router.get('/employees')\n"
        "    async def list_employees():\n"
        "        return {'success': True, 'data': [{'id': emp_id, 'label': LABEL, 'summary': ''}]}\n\n"
        "    @router.post('/employees/' + emp_id + '/run')\n"
        "    async def emp_run(payload: Dict[str, Any] | None = None):\n"
        "        return await _dispatch_run(mod_id, emp_id, stem, payload)\n\n"
        "    @router.get('/employees/' + emp_id + '/status')\n"
        "    async def emp_status():\n"
        "        return {'success': True, 'data': {'employee_id': emp_id, 'status': 'ready'}}\n\n"
        "    app.include_router(router)\n"
        '    logger.info("employee_pack routes registered mod_id=%s emp=%s", mod_id, emp_id)\n\n\n'
        "def mod_init():\n"
        "    logger.info('employee_pack backend init')\n"
    )
