"""受控 Python 客户端代码生成器。

不从 OpenAPI spec 中拼接任意可执行表达式：所有生成代码只是结构化元数据加上一个固定的运行时
派发函数调用。运行时再由 :mod:`openapi_connector_runtime` 加载并执行。

生成产物路径：``data/generated_connectors/{connector_id}/v{version}/``，包含：
- ``__init__.py``  导出 ``OPERATIONS``、``BASE_URL``、``SPEC_HASH``、``call_operation``
- ``client.py``    每个 operation 一个同步函数（参数即 ``params`` / ``body`` / ``headers``）
- ``operations.json``  机器可读元数据
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Sequence

from modstore_server.openapi_connector_parser import ParsedOperation, ParsedSpec


_HEADER = (
    '"""Auto-generated OpenAPI connector client. Do NOT edit by hand."""\n'
    "from __future__ import annotations\n\n"
    "from typing import Any, Dict, Optional\n\n"
    "from modstore_server.openapi_connector_runtime import call_generated_operation\n"
)


def default_artifacts_root() -> Path:
    """生成产物根目录，可通过 ``MODSTORE_OPENAPI_GEN_ROOT`` 覆盖。"""
    import os

    raw = (os.environ.get("MODSTORE_OPENAPI_GEN_ROOT") or "").strip()
    if raw:
        return Path(raw).expanduser().resolve()
    return Path(__file__).resolve().parent / "data" / "generated_connectors"


@dataclass
class GeneratedArtifacts:
    connector_id: int
    version: int
    root: Path
    package_dir: Path
    client_file: Path
    metadata_file: Path
    operation_count: int


def _sanitize_python_identifier(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", str(name or "")).strip("_")
    if not s:
        s = "operation"
    if s[0].isdigit():
        s = "op_" + s
    return s[:80]


def _format_function(op: ParsedOperation) -> str:
    symbol = _sanitize_python_identifier(op.generated_symbol or op.operation_id)
    summary = (op.summary or op.description or op.operation_id).replace("\n", " ").strip()
    summary_safe = summary.replace('"""', "'''")[:300]
    return (
        f"\ndef {symbol}(\n"
        f"    *,\n"
        f"    connector_id: int,\n"
        f"    user_id: int,\n"
        f"    params: Optional[Dict[str, Any]] = None,\n"
        f"    body: Any = None,\n"
        f"    headers: Optional[Dict[str, str]] = None,\n"
        f"    timeout: float = 30.0,\n"
        f"    source: str = \"manual\",\n"
        f") -> Dict[str, Any]:\n"
        f'    """{summary_safe}"""\n'
        f"    return call_generated_operation(\n"
        f"        connector_id=connector_id,\n"
        f"        user_id=user_id,\n"
        f"        operation_id={op.operation_id!r},\n"
        f"        params=params,\n"
        f"        body=body,\n"
        f"        headers=headers,\n"
        f"        timeout=timeout,\n"
        f"        source=source,\n"
        f"    )\n"
    )


def _build_init_module(
    connector_id: int,
    version: int,
    base_url: str,
    spec_hash: str,
    operations: Sequence[ParsedOperation],
) -> str:
    op_meta = [op.to_metadata() for op in operations]
    return (
        '"""Auto-generated OpenAPI connector package.\n'
        "Generated by modstore_server.openapi_connector_codegen.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        f"CONNECTOR_ID = {connector_id}\n"
        f"GENERATED_VERSION = {version}\n"
        f"BASE_URL = {base_url!r}\n"
        f"SPEC_HASH = {spec_hash!r}\n"
        f"OPERATIONS = {json.dumps(op_meta, ensure_ascii=False)}\n"
        "from .client import *  # noqa: F401,F403\n"
    )


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def generate_client_files(
    parsed: ParsedSpec,
    *,
    connector_id: int,
    version: int,
    artifacts_root: Optional[Path] = None,
) -> GeneratedArtifacts:
    root = (artifacts_root or default_artifacts_root()) / str(connector_id) / f"v{version}"
    _ensure_dir(root)
    init_file = root / "__init__.py"
    client_file = root / "client.py"
    metadata_file = root / "operations.json"

    operations = list(parsed.operations)
    init_file.write_text(
        _build_init_module(connector_id, version, parsed.base_url, parsed.spec_hash, operations),
        encoding="utf-8",
    )
    body = _HEADER + "\n" + "\n".join(_format_function(op) for op in operations)
    client_file.write_text(body, encoding="utf-8")
    metadata_file.write_text(
        json.dumps(
            {
                "connector_id": connector_id,
                "version": version,
                "title": parsed.title,
                "spec_version": parsed.version,
                "base_url": parsed.base_url,
                "spec_hash": parsed.spec_hash,
                "operations": [op.to_metadata() for op in operations],
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return GeneratedArtifacts(
        connector_id=connector_id,
        version=version,
        root=root,
        package_dir=root,
        client_file=client_file,
        metadata_file=metadata_file,
        operation_count=len(operations),
    )


def cleanup_old_versions(
    connector_id: int,
    *,
    keep_versions: Iterable[int],
    artifacts_root: Optional[Path] = None,
) -> None:
    """清理旧版本目录，保留 ``keep_versions`` 列出的版本。"""
    root = (artifacts_root or default_artifacts_root()) / str(connector_id)
    if not root.is_dir():
        return
    keep = {f"v{v}" for v in keep_versions}
    for child in root.iterdir():
        if not child.is_dir():
            continue
        if child.name in keep:
            continue
        try:
            shutil.rmtree(child)
        except OSError:
            pass


def load_operations_metadata(
    connector_id: int,
    version: int,
    *,
    artifacts_root: Optional[Path] = None,
) -> Dict[str, Any]:
    root = (artifacts_root or default_artifacts_root()) / str(connector_id) / f"v{version}"
    metadata_file = root / "operations.json"
    if not metadata_file.is_file():
        return {}
    try:
        return json.loads(metadata_file.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
